import { useApp } from "../context/AppContext";

export default function Terms() {
  const { isDark } = useApp();
  const bg = isDark ? "bg-[#09090e] text-slate-100" : "bg-white text-slate-900";
  const textStrong = isDark ? "text-white" : "text-slate-950";
  const textMuted = isDark ? "text-slate-400" : "text-slate-500";
  const bodyText = isDark ? "text-slate-300" : "text-slate-700";
  const h2 = isDark ? "text-slate-100" : "text-slate-900";

  return (
    <div className={`min-h-screen py-20 transition-colors duration-300 ${bg}`}>
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <h1 className={`text-4xl font-black tracking-tight ${textStrong}`}>Terms of Service</h1>
        <p className={`mt-3 text-sm ${textMuted}`}>Last updated: May 2026</p>

        <div className={`mt-10 space-y-8 text-base leading-relaxed ${bodyText}`}>
          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>1. Acceptance of Terms</h2>
            <p>
              By accessing, browsing, or utilizing the web utilities provided by EPUBForge (referred to as "the Service", "we", "us", or "our"), you explicitly agree to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are strictly prohibited from using or accessing this site.
            </p>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>2. Permitted Use & Service Architecture</h2>
            <p>
              EPUBForge provides a local-first, client-side browser interface allowing users to format, manipulate, and convert digital files (such as PDF and EPUB variants). Permission is granted to utilize these web tools for personal, academic, or commercial document processing workflows. This is the grant of a usage license, not a transfer of title, and under this license you may not:
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>Systematically download, archive, replicate, or mirror the core compilation scripts or structural application design layouts on any other server or framework.</li>
              <li>Attempt to decompile, reverse-engineer, deobfuscate, or extract the client-side processing engines or source assets contained on the platform.</li>
              <li>Remove any copyright, digital watermark identifiers, or other proprietary notations from the application's distribution code.</li>
            </ul>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>3. Fair Usage and Automated Abuse Policy</h2>
            <p>
              To preserve infrastructural stability, maintain edge delivery bandwidth, and protect performance parameters for all users, you agree not to abuse our application environment. 
            </p>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>You must not execute automated scripts, scrapers, recursive directory crawlers, or high-frequency automated requests that generate unnatural data loads or proxy-looping errors against our hosting endpoints.</li>
              <li>We reserve the right to deploy edge network defenses, custom firewalls, or automatic rate-limiting blocks (via providers like Cloudflare and Vercel) to instantly terminate access for any user or automated entity found violating these browsing boundaries.</li>
            </ul>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>4. Disclaimer of Warranties</h2>
            <p>
              The materials and web utilities on EPUBForge are provided strictly on an "as is" and "as available" basis. EPUBForge makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. 
            </p>
            <p className="mt-2">
              Furthermore, because all conversions process entirely within your local browser sandbox, EPUBForge does not warrant or make any representations concerning the absolute accuracy, intended layout preservation, or reliability of the file conversions generated by the tool.
            </p>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>5. Limitations of Liability</h2>
            <p>
              In no event shall EPUBForge, its creators, or its infrastructure suppliers be held liable for any structural damages (including, without limitation, damages for loss of data, loss of business profit, hardware degradation, or operational interruptions) arising out of the use, execution, or inability to use the local utilities on our web platform, even if an authorized representative has been notified orally or in writing of the possibility of such damage.
            </p>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>6. External Links and User-Generated Content</h2>
            <p>
              Our website may contain links to third-party platforms, blogs, or resources. EPUBForge has not extensively reviewed all external targets routed through these links and is not responsible for the structural content, privacy procedures, or security postures of any such linked site. The inclusion of any link does not imply endorsement, and navigating to any linked asset is entirely at the user's own risk.
            </p>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>7. Governing Law</h2>
            <p>
              Any legal claim, dispute, or infrastructural action relating to the operational boundaries of EPUBForge shall be governed by and construed in accordance with local jurisdictional statutory tracks, without regard to its conflict of law provisions.
            </p>
          </div>

          <div>
            <h2 className={`mb-3 text-xl font-bold ${h2}`}>8. Revisions and Term Status</h2>
            <p>
              We maintain the right to update or adjust these Terms of Service at any time without issuing an explicit individual alert notice. By continuing to interact with the platform, you recognize that you are actively bound by the most current version of this legal document.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}